import type { FoodVaultNutritionFacts, FoodVaultProduct } from "@/types/commerce";

const pantryNutrition = (
  serving: string,
  servings: string,
  energy: [string, string],
  protein: [string, string],
  fat: [string, string],
  carbs: [string, string],
  sugars: [string, string],
  sodium: [string, string]
): FoodVaultNutritionFacts => ({
  serving_size: serving,
  servings_per_pack: servings,
  rows: [
    { label: "Energy", per_serve: energy[0], per_100g: energy[1] },
    { label: "Protein", per_serve: protein[0], per_100g: protein[1] },
    { label: "Fat, total", per_serve: fat[0], per_100g: fat[1] },
    { label: "Carbohydrate", per_serve: carbs[0], per_100g: carbs[1] },
    { label: "— sugars", per_serve: sugars[0], per_100g: sugars[1] },
    { label: "Sodium", per_serve: sodium[0], per_100g: sodium[1] },
  ],
});

/** Mirrors supabase/seed.sql so the storefront can render before seed is applied. */
export const VAULT_MARKET_SEED_PRODUCTS: FoodVaultProduct[] = [
  {
    id: "seed-fv-cond-stk-430",
    sku: "FV-COND-STK-430",
    name: "Stokes Real Mayonnaise 430g",
    brand: "Stokes",
    retail_price: 12.9,
    member_price: 9.7,
    stock_quantity: 48,
    category: "Pantry",
    subcategory: "Oil, Vinegar & Condiments",
    slug: "stokes-real-mayonnaise-430g",
    image_url:
      "https://images.unsplash.com/photo-1506368083636-6defb67639a7?w=800&h=800&fit=crop",
    gallery_urls: [
      "https://images.unsplash.com/photo-1474979266405-7eaacbcd87c5?w=800&h=800&fit=crop",
    ],
    is_active: true,
    description:
      "A rich British mayonnaise made with free-range eggs and cold-pressed rapeseed oil.",
    ingredients: "Rapeseed oil, free range egg yolk, water, spirit vinegar, sugar, salt, mustard.",
    allergens: "Contains egg and mustard.",
    origin_label: "Made in the United Kingdom",
    net_weight_g: 430,
    health_star_rating: 2,
    nutrition_facts: pantryNutrition(
      "15g",
      "28",
      ["440 kJ", "2930 kJ"],
      ["0.3 g", "1.8 g"],
      ["11.4 g", "76.0 g"],
      ["0.4 g", "2.6 g"],
      ["0.3 g", "2.1 g"],
      ["90 mg", "600 mg"]
    ),
  },
  {
    id: "seed-fv-bisc-cab-200",
    sku: "FV-BISC-CAB-200",
    name: "All Butter Shortbread Rounds 200g",
    brand: "Cartwright & Butler",
    retail_price: 17.5,
    member_price: 13.2,
    stock_quantity: 36,
    category: "Pantry",
    subcategory: "Biscuits & Crackers",
    slug: "all-butter-shortbread-rounds-200g",
    image_url:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=800&fit=crop",
    gallery_urls: [
      "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=800&fit=crop",
    ],
    is_active: true,
    description: "All-butter Scottish-style shortbread rounds in a gift-ready tin.",
    ingredients: "Wheat flour, butter (31%), sugar, salt.",
    allergens: "Contains gluten and milk. May contain traces of nuts.",
    origin_label: "Made in the United Kingdom",
    net_weight_g: 200,
    health_star_rating: 1.5,
    nutrition_facts: pantryNutrition(
      "25g",
      "8",
      ["545 kJ", "2180 kJ"],
      ["1.4 g", "5.6 g"],
      ["7.6 g", "30.4 g"],
      ["14.2 g", "56.8 g"],
      ["4.8 g", "19.2 g"],
      ["85 mg", "340 mg"]
    ),
  },
  {
    id: "seed-fv-tea-fam-125",
    sku: "FV-TEA-FAM-125",
    name: "Royal Blend Loose Leaf Tea 125g",
    brand: "Fortnum & Mason",
    retail_price: 34,
    member_price: 25.5,
    stock_quantity: 24,
    category: "Drinks",
    subcategory: "Tea & Milk Drinks",
    slug: "royal-blend-loose-leaf-tea-125g",
    image_url:
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=800&h=800&fit=crop",
    gallery_urls: [
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=800&fit=crop",
    ],
    is_active: true,
    description: "A classic Ceylon and Yunnan blend first created for King Edward VII.",
    ingredients: "Black tea.",
    allergens: "May contain traces of nuts if packed in a shared facility.",
    origin_label: "Packed in the United Kingdom",
    net_weight_g: 125,
    health_star_rating: 5,
    nutrition_facts: pantryNutrition(
      "2g",
      "62",
      ["4 kJ", "200 kJ"],
      ["0.1 g", "5.0 g"],
      ["0.0 g", "0.1 g"],
      ["0.0 g", "0.5 g"],
      ["0.0 g", "0.0 g"],
      ["1 mg", "20 mg"]
    ),
  },
  {
    id: "seed-fv-cond-trk-300",
    sku: "FV-COND-TRK-300",
    name: "Tracklements Onion Marmalade 300g",
    brand: "Tracklements",
    retail_price: 14.9,
    member_price: 11.2,
    stock_quantity: 40,
    category: "Pantry",
    subcategory: "Oil, Vinegar & Condiments",
    slug: "tracklements-onion-marmalade-300g",
    image_url:
      "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&h=800&fit=crop",
    is_active: true,
    description: "Slow-cooked onions with cider vinegar and raw cane sugar.",
    ingredients: "Onions (54%), raw cane sugar, cider vinegar, spices, salt.",
    allergens: "None of the common allergens.",
    origin_label: "Made in the United Kingdom",
    net_weight_g: 300,
    health_star_rating: 2.5,
    nutrition_facts: pantryNutrition(
      "15g",
      "20",
      ["145 kJ", "967 kJ"],
      ["0.2 g", "1.1 g"],
      ["0.0 g", "0.2 g"],
      ["8.2 g", "54.7 g"],
      ["7.9 g", "52.6 g"],
      ["45 mg", "300 mg"]
    ),
  },
  {
    id: "seed-fv-bisc-mcv-250",
    sku: "FV-BISC-MCV-250",
    name: "McVitie's Dark Chocolate Digestives 250g",
    brand: "McVitie's",
    retail_price: 6.8,
    member_price: 5.1,
    stock_quantity: 60,
    category: "Pantry",
    subcategory: "Biscuits & Crackers",
    slug: "mcvities-dark-chocolate-digestives-250g",
    image_url:
      "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=800&fit=crop",
    is_active: true,
    description: "Wheat digestive biscuits topped with a layer of dark chocolate.",
    ingredients: "Wheat flour, dark chocolate (30%), vegetable oil, sugar, wholemeal wheat flour.",
    allergens: "Contains gluten and soy. May contain milk.",
    origin_label: "Made in the United Kingdom",
    net_weight_g: 250,
    health_star_rating: 1.5,
    nutrition_facts: pantryNutrition(
      "17g",
      "15",
      ["348 kJ", "2047 kJ"],
      ["1.1 g", "6.3 g"],
      ["4.4 g", "25.7 g"],
      ["10.1 g", "59.4 g"],
      ["4.6 g", "27.0 g"],
      ["80 mg", "470 mg"]
    ),
  },
  {
    id: "seed-fv-tea-twn-100",
    sku: "FV-TEA-TWN-100",
    name: "Twinings Earl Grey 100 Tea Bags",
    brand: "Twinings",
    retail_price: 12.4,
    member_price: 9.3,
    stock_quantity: 55,
    category: "Drinks",
    subcategory: "Tea & Milk Drinks",
    slug: "twinings-earl-grey-100-tea-bags",
    image_url:
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=800&fit=crop",
    is_active: true,
    description: "Ceylon and Assam teas scented with bergamot.",
    ingredients: "Black tea, bergamot flavouring.",
    allergens: "None of the common allergens.",
    origin_label: "Packed in the United Kingdom",
    net_weight_g: 200,
    health_star_rating: 5,
    unit_pricing: { price: 4.65, basis: "100 bags" },
    nutrition_facts: pantryNutrition(
      "2g",
      "100",
      ["4 kJ", "200 kJ"],
      ["0.1 g", "5.0 g"],
      ["0.0 g", "0.0 g"],
      ["0.0 g", "0.3 g"],
      ["0.0 g", "0.0 g"],
      ["1 mg", "15 mg"]
    ),
  },
  {
    id: "seed-fv-oil-fbo-500",
    sku: "FV-OIL-FBO-500",
    name: "Filippo Berio Extra Virgin Olive Oil 500ml",
    brand: "Filippo Berio",
    retail_price: 18.9,
    member_price: 14.2,
    stock_quantity: 32,
    category: "Pantry",
    subcategory: "Oil, Vinegar & Condiments",
    slug: "filippo-berio-extra-virgin-olive-oil-500ml",
    image_url:
      "https://images.unsplash.com/photo-1474979266405-7eaacbcd87c5?w=800&h=800&fit=crop",
    is_active: true,
    description: "Cold-extracted Italian extra virgin olive oil for finishing and dressing.",
    ingredients: "Extra virgin olive oil.",
    allergens: "None of the common allergens.",
    origin_label: "Packed in Italy",
    health_star_rating: 3.5,
    nutrition_facts: pantryNutrition(
      "15ml",
      "33",
      ["510 kJ", "3400 kJ"],
      ["0.0 g", "0.0 g"],
      ["13.8 g", "92.0 g"],
      ["0.0 g", "0.0 g"],
      ["0.0 g", "0.0 g"],
      ["0 mg", "0 mg"]
    ),
  },
  {
    id: "seed-fv-sweet-wtk-180",
    sku: "FV-SWEET-WTK-180",
    name: "Whittaker's Creamy Milk Mini Slabs 180g",
    brand: "Whittaker's",
    retail_price: 8.5,
    member_price: 6.4,
    stock_quantity: 70,
    category: "Pantry",
    subcategory: "Snacks & Sweets",
    slug: "whittakers-creamy-milk-mini-slabs-180g",
    image_url:
      "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&h=800&fit=crop",
    is_active: true,
    description: "New Zealand 33% cocoa creamy milk chocolate mini slabs.",
    ingredients: "Sugar, cocoa butter, whole milk powder, cocoa mass, emulsifier (soy lecithin).",
    allergens: "Contains milk and soy. May contain traces of peanuts and tree nuts.",
    origin_label: "Made in New Zealand",
    net_weight_g: 180,
    health_star_rating: 1,
    nutrition_facts: pantryNutrition(
      "25g",
      "7.2",
      ["568 kJ", "2270 kJ"],
      ["1.8 g", "7.2 g"],
      ["8.4 g", "33.6 g"],
      ["13.6 g", "54.4 g"],
      ["13.2 g", "52.8 g"],
      ["20 mg", "80 mg"]
    ),
  },
  {
    id: "seed-fv-spread-bm-370",
    sku: "FV-SPREAD-BM-370",
    name: "Bonne Maman Strawberry Conserve 370g",
    brand: "Bonne Maman",
    retail_price: 9.9,
    member_price: 7.4,
    stock_quantity: 44,
    category: "Pantry",
    subcategory: "Cereals & Spreads",
    slug: "bonne-maman-strawberry-conserve-370g",
    image_url:
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&h=800&fit=crop",
    is_active: true,
    description: "French strawberry conserve made with whole fruit and cane sugar.",
    ingredients: "Strawberries, sugar, brown cane sugar, concentrated lemon juice, fruit pectin.",
    allergens: "None of the common allergens.",
    origin_label: "Made in France",
    net_weight_g: 370,
    health_star_rating: 2,
    nutrition_facts: pantryNutrition(
      "20g",
      "18",
      ["196 kJ", "980 kJ"],
      ["0.1 g", "0.4 g"],
      ["0.0 g", "0.1 g"],
      ["11.4 g", "57.0 g"],
      ["11.2 g", "56.0 g"],
      ["2 mg", "10 mg"]
    ),
  },
  {
    id: "seed-fv-tea-yt-80",
    sku: "FV-TEA-YT-80",
    name: "Yorkshire Tea 80 Tea Bags",
    brand: "Taylors of Harrogate",
    retail_price: 8.2,
    member_price: 6.15,
    stock_quantity: 50,
    category: "Drinks",
    subcategory: "Tea & Milk Drinks",
    slug: "yorkshire-tea-80-tea-bags",
    image_url:
      "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&h=800&fit=crop",
    is_active: true,
    description: "A proper brew from Yorkshire, blended from African and Indian teas.",
    ingredients: "Black tea.",
    allergens: "None of the common allergens.",
    origin_label: "Packed in the United Kingdom",
    health_star_rating: 5,
    unit_pricing: { price: 7.69, basis: "100 bags" },
    nutrition_facts: pantryNutrition(
      "2g",
      "80",
      ["4 kJ", "200 kJ"],
      ["0.1 g", "5.0 g"],
      ["0.0 g", "0.0 g"],
      ["0.0 g", "0.3 g"],
      ["0.0 g", "0.0 g"],
      ["1 mg", "15 mg"]
    ),
  },
];
