import { NZ_REGIONS, type NzRegion } from "@/lib/hospitality/constants";

export const NZ_LOCALITIES_BY_REGION: Record<NzRegion, readonly string[]> = {
  Northland: [
    "Whangārei",
    "Kamo",
    "Tikipunga",
    "Onerahi",
    "Kensington",
    "Kerikeri",
    "Paihia",
    "Russell",
    "Waitangi",
    "Kaitaia",
    "Ahipara",
    "Mangonui",
    "Coopers Beach",
    "Doubtless Bay",
    "Kaikohe",
    "Kawakawa",
    "Moerewa",
    "Dargaville",
    "Ruawai",
    "Mangawhai",
    "Mangawhai Heads",
    "Waipu",
    "Ruakākā",
    "One Tree Point",
    "Hikurangi",
    "Opua",
    "Rawene",
    "Opononi",
    "Omapere",
    "Hokianga",
  ],
  Auckland: [
    "Auckland",
    "Auckland CBD",
    "City Centre",
    "Viaduct Harbour",
    "Wynyard Quarter",
    "Ponsonby",
    "Grey Lynn",
    "Kingsland",
    "Arch Hill",
    "Herne Bay",
    "St Marys Bay",
    "Freemans Bay",
    "Newton",
    "Eden Terrace",
    "Grafton",
    "Parnell",
    "Newmarket",
    "Remuera",
    "Orakei",
    "Mission Bay",
    "Kohimarama",
    "St Heliers",
    "Glendowie",
    "Meadowbank",
    "St Johns",
    "Glen Innes",
    "Point England",
    "Panmure",
    "Mount Eden",
    "Mount Albert",
    "Sandringham",
    "Balmoral",
    "Epsom",
    "Greenlane",
    "One Tree Hill",
    "Ellerslie",
    "Penrose",
    "Onehunga",
    "Royal Oak",
    "Hillsborough",
    "Three Kings",
    "Mount Roskill",
    "Lynfield",
    "Blockhouse Bay",
    "Avondale",
    "New Lynn",
    "Kelston",
    "Glen Eden",
    "Titirangi",
    "Green Bay",
    "Henderson",
    "Te Atatū Peninsula",
    "Te Atatū South",
    "Glendene",
    "Sunnyvale",
    "Swanson",
    "Ranui",
    "Massey",
    "Westgate",
    "Hobsonville",
    "Whenuapai",
    "West Harbour",
    "Herald Island",
    "Takapuna",
    "Devonport",
    "Narrow Neck",
    "Bayswater",
    "Belmont",
    "Hauraki",
    "Milford",
    "Forrest Hill",
    "Sunnycove",
    "Castor Bay",
    "Campbells Bay",
    "Mairangi Bay",
    "Murrays Bay",
    "Rothesay Bay",
    "Browns Bay",
    "Torbay",
    "Long Bay",
    "Albany",
    "Rosedale",
    "Glenfield",
    "Birkenhead",
    "Northcote",
    "Hillcrest",
    "Wairau Valley",
    "Unsworth Heights",
    "Greenhithe",
    "Beach Haven",
    "Birkdale",
    "Orewa",
    "Silverdale",
    "Whangaparāoa",
    "Stanmore Bay",
    "Manly",
    "Red Beach",
    "Gulf Harbour",
    "Warkworth",
    "Snells Beach",
    "Wellsford",
    "Helensville",
    "Kumeu",
    "Huapai",
    "Waimauku",
    "Piha",
    "Karekare",
    "Muriwai",
    "Howick",
    "Pakuranga",
    "Botany",
    "East Tāmaki",
    "Dannemora",
    "Flat Bush",
    "Half Moon Bay",
    "Bucklands Beach",
    "Eastern Beach",
    "Mellons Bay",
    "Cockle Bay",
    "Shelly Park",
    "Somerville",
    "Northpark",
    "Golflands",
    "Highland Park",
    "Farm Cove",
    "Sunnyhills",
    "Manukau",
    "Manukau City Centre",
    "Papatoetoe",
    "Ōtara",
    "Clover Park",
    "Wiri",
    "Māngere",
    "Māngere Bridge",
    "Māngere East",
    "Favona",
    "Ōtāhuhu",
    "Middlemore",
    "Papakura",
    "Takanini",
    "Conifer Grove",
    "Drury",
    "Pukekohe",
    "Waiuku",
    "Tuakau",
    "Clevedon",
    "Beachlands",
    "Maraetai",
    "Whitford",
    "Waiheke Island",
    "Oneroa",
    "Ostend",
    "Palm Beach",
    "Great Barrier Island",
  ],
  Waikato: [
    "Hamilton",
    "Hamilton Central",
    "Hamilton East",
    "Frankton",
    "Chartwell",
    "Rototuna",
    "Flagstaff",
    "The Base",
    "Te Rapa",
    "Dinsdale",
    "Hillcrest",
    "Claudelands",
    "Cambridge",
    "Leamington",
    "Te Awamutu",
    "Kihikihi",
    "Pirongia",
    "Huntly",
    "Ngaruawahia",
    "Taupiri",
    "Morrinsville",
    "Matamata",
    "Putaruru",
    "Tokoroa",
    "Tirau",
    "Te Aroha",
    "Paeroa",
    "Waihi",
    "Thames",
    "Whitianga",
    "Whangamatā",
    "Pauanui",
    "Tairua",
    "Coromandel",
    "Mercury Bay",
    "Raglan",
    "Te Kauwhata",
    "Meremere",
    "Taupō",
    "Acacia Bay",
    "Kinloch",
    "Turangi",
    "Mangakino",
    "Ōtorohanga",
    "Te Kūiti",
    "Waitomo",
  ],
  "Bay of Plenty": [
    "Tauranga",
    "Tauranga Central",
    "Mount Maunganui",
    "Papamoa",
    "Papamoa Beach",
    "Welcome Bay",
    "Hairini",
    "Greerton",
    "Gate Pa",
    "Otumoetai",
    "Matua",
    "Bethlehem",
    "Pyes Pa",
    "The Lakes",
    "Omokoroa",
    "Te Puna",
    "Katikati",
    "Waihi Beach",
    "Te Puke",
    "Maketu",
    "Pāpāmoa East",
    "Rotorua",
    "Rotorua Central",
    "Fenton Street",
    "Ngongotahā",
    "Lynmore",
    "Owhata",
    "Whakatāne",
    "Ōhope",
    "Coastlands",
    "Kawerau",
    "Edgecumbe",
    "Matatā",
    "Ōpōtiki",
  ],
  Gisborne: [
    "Gisborne",
    "Gisborne Central",
    "Kaiti",
    "Whataupoko",
    "Te Hapara",
    "Elgin",
    "Outer Kaiti",
    "Makaraka",
    "Wainui",
    "Okitu",
    "Tolaga Bay",
    "Tokomaru Bay",
    "Ruatoria",
    "Te Karaka",
  ],
  "Hawke's Bay": [
    "Napier",
    "Napier Central",
    "Ahuriri",
    "Westshore",
    "Bluff Hill",
    "Hospital Hill",
    "Marewa",
    "Onekawa",
    "Tamatea",
    "Pirimai",
    "Taradale",
    "Greenmeadows",
    "Meeanee",
    "Awatoto",
    "Bay View",
    "Hastings",
    "Hastings Central",
    "Havelock North",
    "Flaxmere",
    "Camberley",
    "Mahora",
    "Parkvale",
    "Akina",
    "Raureka",
    "Stortford Lodge",
    "Clive",
    "Haumoana",
    "Te Awanga",
    "Waimarama",
    "Waipukurau",
    "Waipawa",
    "Otane",
    "Wairoa",
  ],
  Taranaki: [
    "New Plymouth",
    "New Plymouth Central",
    "Fitzroy",
    "Strandon",
    "East End",
    "Westown",
    "Lynmouth",
    "Spotswood",
    "Marfell",
    "Merrilands",
    "Highlands Park",
    "Bell Block",
    "Waitara",
    "Inglewood",
    "Oakura",
    "Ōkato",
    "Urenui",
    "Stratford",
    "Eltham",
    "Hāwera",
    "Patea",
    "Waverley",
    "Opunake",
    "Manaia",
  ],
  "Manawatū-Whanganui": [
    "Palmerston North",
    "Palmerston North Central",
    "Hokowhitu",
    "Terrace End",
    "Takaro",
    "Highbury",
    "Awapuni",
    "West End",
    "Milson",
    "Kelvin Grove",
    "Aokautere",
    "Ashhurst",
    "Feilding",
    "Bunnythorpe",
    "Longburn",
    "Whanganui",
    "Whanganui Central",
    "St Johns Hill",
    "Gonville",
    "Castlecliff",
    "Aramoho",
    "Springvale",
    "Levin",
    "Foxton",
    "Foxton Beach",
    "Shannon",
    "Tokomaru",
    "Otaki",
    "Waitarere Beach",
    "Dannevirke",
    "Woodville",
    "Pahiatua",
    "Eketāhuna",
    "Taihape",
    "Ohakune",
    "Raetihi",
    "National Park",
    "Taumarunui",
    "Marton",
    "Bulls",
    "Sanson",
  ],
  Wellington: [
    "Wellington",
    "Wellington Central",
    "Te Aro",
    "Lambton",
    "Pipitea",
    "Thorndon",
    "Kelburn",
    "Aro Valley",
    "Mount Victoria",
    "Oriental Bay",
    "Roseneath",
    "Hataitai",
    "Kilbirnie",
    "Lyall Bay",
    "Houghton Bay",
    "Island Bay",
    "Berhampore",
    "Newtown",
    "Mount Cook",
    "Brooklyn",
    "Vogeltown",
    "Mornington",
    "Kingston",
    "Happy Valley",
    "Karori",
    "Northland",
    "Wilton",
    "Wadestown",
    "Crofton Downs",
    "Ngaio",
    "Khandallah",
    "Johnsonville",
    "Newlands",
    "Paparangi",
    "Grenada Village",
    "Churton Park",
    "Tawa",
    "Linden",
    "Miramar",
    "Strathmore Park",
    "Seatoun",
    "Breaker Bay",
    "Rongotai",
    "Lower Hutt",
    "Petone",
    "Eastbourne",
    "Wainuiomata",
    "Naenae",
    "Taita",
    "Stokes Valley",
    "Avalon",
    "Epuni",
    "Waterloo",
    "Woburn",
    "Hutt Central",
    "Alicetown",
    "Moera",
    "Waiwhetu",
    "Gracefield",
    "Seaview",
    "Days Bay",
    "York Bay",
    "Upper Hutt",
    "Trentham",
    "Heretaunga",
    "Silverstream",
    "Pinehaven",
    "Totara Park",
    "Maoribank",
    "Brown Owl",
    "Te Marua",
    "Porirua",
    "Porirua Central",
    "Waitangirua",
    "Cannons Creek",
    "Ascot Park",
    "Whitby",
    "Paremata",
    "Pāuatahanui",
    "Plimmerton",
    "Pukerua Bay",
    "Titahi Bay",
    "Elsdon",
    "Takapūwāhia",
    "Masterton",
    "Carterton",
    "Greytown",
    "Featherston",
    "Martinborough",
    "Paraparaumu",
    "Paraparaumu Beach",
    "Raumati Beach",
    "Raumati South",
    "Waikanae",
    "Waikanae Beach",
    "Paekākāriki",
    "Ōtaki",
    "Ōtaki Beach",
  ],
  Tasman: [
    "Richmond",
    "Hope",
    "Brightwater",
    "Wakefield",
    "Māpua",
    "Ruby Bay",
    "Motueka",
    "Riwaka",
    "Kaiteriteri",
    "Mārahau",
    "Takaka",
    "Collingwood",
    "Pōhara",
    "Golden Bay",
    "Murchison",
    "St Arnaud",
  ],
  Nelson: [
    "Nelson",
    "Nelson Central",
    "The Wood",
    "Washington Valley",
    "Port Nelson",
    "Tahunanui",
    "Stoke",
    "Enner Glynn",
    "Nayland",
    "Monaco",
    "Annesbrook",
    "Wakatu",
    "Atawhai",
    "Marybank",
    "Hira",
  ],
  Marlborough: [
    "Blenheim",
    "Blenheim Central",
    "Springlands",
    "Redwoodtown",
    "Witherlea",
    "Riversdale",
    "Renwick",
    "Picton",
    "Waikawa",
    "Havelock",
    "Seddon",
    "Ward",
    "Kaikōura",
  ],
  "West Coast": [
    "Greymouth",
    "Cobden",
    "Blaketown",
    "Runanga",
    "Dobson",
    "Moana",
    "Westport",
    "Carters Beach",
    "Reefton",
    "Hokitika",
    "Kaniere",
    "Ross",
    "Harihari",
    "Whataroa",
    "Franz Josef",
    "Fox Glacier",
    "Haast",
    "Punakaiki",
    "Charleston",
    "Karamea",
  ],
  Canterbury: [
    "Christchurch",
    "Christchurch Central",
    "Addington",
    "Riccarton",
    "Ilam",
    "Upper Riccarton",
    "Sockburn",
    "Hornby",
    "Hei Hei",
    "Islington",
    "Templeton",
    "Halswell",
    "Wigram",
    "Aidensfield",
    "Hillmorton",
    "Hoon Hay",
    "Spreydon",
    "Somerfield",
    "Cashmere",
    "Westmorland",
    "Huntsbury",
    "St Martins",
    "Opawa",
    "Waltham",
    "Sydenham",
    "Beckenham",
    "Woolston",
    "Linwood",
    "Phillipstown",
    "Avonside",
    "Richmond",
    "Shirley",
    "Mairehau",
    "St Albans",
    "Merivale",
    "Fendalton",
    "Bryndwr",
    "Burnside",
    "Avonhead",
    "Russley",
    "Harewood",
    "Bishopdale",
    "Casebrook",
    "Papanui",
    "Redwood",
    "Northcote",
    "Styx",
    "Belfast",
    "Marshland",
    "Burwood",
    "Parklands",
    "New Brighton",
    "North New Brighton",
    "South New Brighton",
    "Southshore",
    "New Brighton Pier",
    "Aranui",
    "Wainoni",
    "Bromley",
    "Ferrymead",
    "Heathcote",
    "Sumner",
    "Redcliffs",
    "Mount Pleasant",
    "Lyttelton",
    "Governors Bay",
    "Diamond Harbour",
    "Akaroa",
    "Rolleston",
    "Lincoln",
    "Prebbleton",
    "West Melton",
    "Tai Tapu",
    "Lincoln University",
    "Rangiora",
    "Kaiapoi",
    "Woodend",
    "Pegasus",
    "Waikuku",
    "Amberley",
    "Oxford",
    "Darfield",
    "Leeston",
    "Southbridge",
    "Ashburton",
    "Tinwald",
    "Methven",
    "Rakaia",
    "Geraldine",
    "Temuka",
    "Timaru",
    "Highfield",
    "Waimataitai",
    "Gleniti",
    "Watlington",
    "Kensington",
    "Washdyke",
    "Pleasant Point",
    "Fairlie",
    "Twizel",
    "Lake Tekapo",
    "Mount Cook Village",
    "Waimate",
    "Kurow",
    "Ōamaru",
  ],
  Otago: [
    "Dunedin",
    "Dunedin Central",
    "The Octagon",
    "North Dunedin",
    "South Dunedin",
    "St Clair",
    "St Kilda",
    "Caversham",
    "Mornington",
    "Roslyn",
    "Maori Hill",
    "Opoho",
    "North East Valley",
    "Pine Hill",
    "Normanby",
    "Gardens",
    "University",
    "Port Chalmers",
    "Ravensbourne",
    "Macandrew Bay",
    "Broad Bay",
    "Portobello",
    "Mosgiel",
    "Brighton",
    "Green Island",
    "Fairfield",
    "Kaikorai",
    "Brockville",
    "Halfway Bush",
    "Wakari",
    "Helensburgh",
    "Waverley",
    "Andersons Bay",
    "Tainui",
    "Musselburgh",
    "Queenstown",
    "Frankton",
    "Kelvin Heights",
    "Fernhill",
    "Sunshine Bay",
    "Arthurs Point",
    "Arrowtown",
    "Lake Hayes",
    "Shotover Country",
    "Jack's Point",
    "Wanaka",
    "Albert Town",
    "Hāwea",
    "Luggate",
    "Cromwell",
    "Bannockburn",
    "Alexandra",
    "Clyde",
    "Roxburgh",
    "Ranfurly",
    "Oamaru",
    "Weston",
    "Palmerston",
    "Waikouaiti",
    "Balclutha",
    "Milton",
    "Lawrence",
  ],
  Southland: [
    "Invercargill",
    "Invercargill Central",
    "Windsor",
    "Gladstone",
    "Waikiwi",
    "Grasmere",
    "Hawthorndale",
    "Heidelberg",
    "Kew",
    "Strathern",
    "Newfield",
    "Georgetown",
    "Appleby",
    "Bluff",
    "Otatara",
    "Gore",
    "Mataura",
    "Winton",
    "Te Anau",
    "Manapouri",
    "Riverton",
    "Otautau",
    "Tuatapere",
    "Lumsden",
    "Queenstown",
    "Milford Sound",
  ],
};

export function listNzLocalitiesForRegion(region?: string | null) {
  if (!region || region === "other") {
    return [...new Set(NZ_REGIONS.flatMap((name) => NZ_LOCALITIES_BY_REGION[name]))].sort(
      (a, b) => a.localeCompare(b)
    );
  }

  const match = NZ_REGIONS.find(
    (name) => name.toLowerCase() === region.trim().toLowerCase()
  );
  return match ? [...NZ_LOCALITIES_BY_REGION[match]] : [];
}

export function filterSuggestions(options: readonly string[], query: string, limit = 12) {
  const needle = query.trim().toLowerCase();
  const ranked = needle
    ? options.filter((option) => option.toLowerCase().includes(needle))
    : [...options];

  ranked.sort((a, b) => {
    if (!needle) return a.localeCompare(b);
    const aStarts = a.toLowerCase().startsWith(needle) ? 0 : 1;
    const bStarts = b.toLowerCase().startsWith(needle) ? 0 : 1;
    return aStarts - bStarts || a.localeCompare(b);
  });

  return ranked.slice(0, limit);
}
