import type {
  ContactEnquiryRow,
  DashboardStats,
  DiscoverArticleRow,
  MemberRow,
  PartnerApplicationRow,
  PartnerRow,
  SystemSettings,
} from "@/lib/admin/types";
import { DEFAULT_SYSTEM_SETTINGS } from "@/lib/system-settings";

export const mockDashboardStats: DashboardStats = {
  activeMembers: 14282,
  paidMembers: 8912,
  livePartners: 432,
  pendingApplications: 28,
  supportEnquiries: 156,
  publishedArticles: 2405,
};

export const mockApplications: PartnerApplicationRow[] = [
  {
    id: "1",
    business_name: "Green Leaf Organics",
    website_url: "https://greenleaf.co.nz",
    primary_category: "Fruit & Veg",
    location: "Auckland, NZ",
    created_at: "2024-10-24T14:20:00Z",
    short_description: "Organic produce delivered weekly.",
    brand_story: "Family-owned organic farm since 2010.",
    discount_value: "15",
    offer_type: "Percentage Discount",
    offer_terms: "Minimum order $50.",
    member_code: "FOODVAULT-GREEN-15",
    support_email: "hello@greenleaf.co.nz",
    support_phone: "+64 21 000 0001",
    banner_image_url: null,
    logo_url: null,
    gallery_image_urls: [],
  },
  {
    id: "2",
    business_name: "Artisan Crust Co.",
    website_url: "https://artisancrust.co.nz",
    primary_category: "Bakery",
    location: "Wellington, NZ",
    created_at: "2024-10-23T09:15:00Z",
    short_description: "Sourdough baked fresh daily.",
    brand_story: "Traditional baking methods.",
    discount_value: "10",
    offer_type: "Percentage Discount",
    offer_terms: "One use per member.",
    member_code: "FOODVAULT-ARTISAN-10",
    support_email: "orders@artisancrust.co.nz",
    support_phone: null,
    banner_image_url: null,
    logo_url: null,
    gallery_image_urls: [],
  },
];

export const mockPartners: PartnerRow[] = [
  {
    id: "p1",
    business_name: "GreenLeaf Wholesale",
    primary_category: "Fresh Produce",
    application_status_v2: "APPROVED",
    listing_status_v2: "LIVE",
    suspended: false,
    approved_at: "2024-10-12T00:00:00Z",
    location: "Auckland",
    member_code: "FOODVAULT-GREEN-15",
  },
  {
    id: "p2",
    business_name: "Nordic Fish Co.",
    primary_category: "Seafood",
    application_status_v2: "APPROVED",
    listing_status_v2: "PENDING",
    suspended: false,
    approved_at: "2024-10-18T00:00:00Z",
    location: "Christchurch",
    member_code: "FOODVAULT-NORDIC-20",
  },
  {
    id: "p3",
    business_name: "Valley Dairy",
    primary_category: "Dairy",
    application_status_v2: "APPLICATION_UNDER_REVIEW",
    listing_status_v2: "PENDING",
    suspended: false,
    approved_at: null,
    location: "Hamilton",
    member_code: null,
  },
  {
    id: "p4",
    business_name: "Urban Spice Farm",
    primary_category: "Pantry",
    application_status_v2: "APPROVED",
    listing_status_v2: "LIVE",
    suspended: true,
    approved_at: "2024-09-01T00:00:00Z",
    location: "Tauranga",
    member_code: "FOODVAULT-SPICE-12",
  },
];

export const mockMembers: MemberRow[] = [
  { id: "m1", email: "john.doe@email.com", full_name: "John Doe", status: "ACTIVE", joined_at: "2024-10-12T00:00:00Z" },
  { id: "m2", email: "sarah.m@email.com", full_name: "Sarah Miller", status: "TRIAL", joined_at: "2024-10-20T00:00:00Z" },
  { id: "m3", email: "rb@email.com", full_name: "Robert Brown", status: "EXPIRED", joined_at: "2024-08-01T00:00:00Z" },
  { id: "m4", email: "kl@email.com", full_name: "Kate Lewis", status: "CANCELLED", joined_at: "2024-06-15T00:00:00Z" },
  { id: "m5", email: "emma@email.com", full_name: "Emma Wilson", status: "ACTIVE", joined_at: "2024-10-22T00:00:00Z" },
];

export const mockRecentMembers = mockMembers.slice(0, 4);

export const mockEnquiries: ContactEnquiryRow[] = [
  {
    id: "e1",
    reference_number: "FV-8842",
    name: "Eleanor Shellstrop",
    email: "eleanor@email.com",
    enquiry_type: "MEMBER",
    subject: "Membership billing question",
    message: "I was charged twice this month.",
    status: "NEW",
    internal_notes: null,
    created_at: "2024-10-24T09:12:00Z",
  },
  {
    id: "e2",
    reference_number: "FV-8841",
    name: "Chidi Anagonye",
    email: "chidi@email.com",
    enquiry_type: "PARTNER",
    subject: "Partner application status",
    message: "When will my application be reviewed?",
    status: "OPEN",
    internal_notes: "Follow up with approvals team.",
    created_at: "2024-10-23T14:30:00Z",
  },
  {
    id: "e3",
    reference_number: "FV-8840",
    name: "Jason Mendoza",
    email: "jason@email.com",
    enquiry_type: "GENERAL",
    subject: "General platform question",
    message: "How do I browse brands?",
    status: "RESOLVED",
    internal_notes: null,
    created_at: "2024-10-22T11:00:00Z",
  },
];

export const mockRecentEnquiries = mockEnquiries.slice(0, 3);

export const mockArticles: DiscoverArticleRow[] = [
  {
    id: "a1",
    title: "Optimizing Logistics: The FoodVault 2024 Roadmap",
    slug: "optimizing-logistics-foodvault-2024",
    category: "Saving",
    status: "PUBLISHED",
    summary: "A look at how brands save on logistics.",
    body: "<p>Content here</p>",
    hero_image_url: null,
    meta_title: "FoodVault 2024 Roadmap",
    meta_description: "Logistics roadmap for partners.",
    meta_tags: ["logistics", "partners", "savings"],
    featured: true,
    publish_date: "2024-10-24T00:00:00Z",
    author_name: "Admin User",
    read_time_minutes: 8,
    views: 1200,
    created_at: "2024-10-20T00:00:00Z",
  },
  {
    id: "a2",
    title: "Best Protein Brands in NZ",
    slug: "best-protein-brands-nz",
    category: "News",
    status: "DRAFT",
    summary: "Top protein brands reviewed.",
    body: null,
    hero_image_url: null,
    meta_title: null,
    meta_description: null,
    meta_tags: [],
    featured: false,
    publish_date: null,
    author_name: "Admin User",
    read_time_minutes: 5,
    views: 0,
    created_at: "2024-10-18T00:00:00Z",
  },
];

export const mockSettings: SystemSettings = {
  platform_name: DEFAULT_SYSTEM_SETTINGS.platform_name,
  membership_price_monthly: DEFAULT_SYSTEM_SETTINGS.membership_price_monthly,
  trial_length_days: DEFAULT_SYSTEM_SETTINGS.trial_length_days,
  support_email: DEFAULT_SYSTEM_SETTINGS.support_email,
  homepage_headline: DEFAULT_SYSTEM_SETTINGS.homepage_headline,
  homepage_subheading: DEFAULT_SYSTEM_SETTINGS.homepage_subheading,
};

export const mockBrandReports: import("@/lib/admin/types").BrandReportRow[] = [
  {
    id: "br-1",
    report_reference: "BR-000127",
    brand_id: "1",
    brand_name: "Wish Bone",
    brand_logo_url: null,
    reporter_user_id: "member-1",
    reporter_email: "member@example.com",
    reason: "incorrect_discounts",
    description: "The advertised 20% discount code did not apply at checkout.",
    contact_permission: true,
    attachment_urls: [],
    status: "New",
    priority: "Medium",
    admin_notes: null,
    assigned_admin_id: null,
    assigned_admin_name: null,
    reviewed_at: null,
    created_at: "2024-10-24T10:00:00Z",
    updated_at: "2024-10-24T10:00:00Z",
  },
  {
    id: "br-2",
    report_reference: "BR-000126",
    brand_id: "2",
    brand_name: "Artisan Crust Co.",
    brand_logo_url: null,
    reporter_user_id: "member-2",
    reporter_email: "another@example.com",
    reason: "scam_fraud",
    description: "Website redirected to a suspicious payment page.",
    contact_permission: false,
    attachment_urls: ["member-2/evidence.pdf"],
    status: "Under Review",
    priority: "Critical",
    admin_notes: "Escalated for manual review.",
    assigned_admin_id: "admin-1",
    assigned_admin_name: "Admin User",
    reviewed_at: null,
    created_at: "2024-10-23T14:30:00Z",
    updated_at: "2024-10-23T16:00:00Z",
  },
];
